/**
 * API 関連の TypeScript 型は **全て** zod スキーマから `z.infer<>` で派生させる。
 * 直接 type を書かない方針 (スキーマと型のドリフトを防ぐ)。
 */

export type {
  // Pagination
  Paginated,
  // Enums
  Role,
  ContractStatus,
  ContractType,
  Confidentiality,
  RiskLevel,
  RiskStatus,
  ReviewStatus,
  ReviewType,
  WorkflowStepStatus,
  WorkflowStepType,
  NotificationChannel,
  NotificationStatus,
  UploadStorage,
  // Entities
  Department,
  UserRef,
  User,
  Attachment,
  Comment,
  Clause,
  Contract,
  ContractCreate,
  ContractUpdate,
  ReviewFinding,
  LegalReview,
  ReviewCreate,
  RiskItem,
  RiskUpdate,
  RiskHeatmap,
  WorkflowStepDefinition,
  Workflow,
  WorkflowStep,
  ComplianceChecklist,
  ComplianceRun,
  ClauseLibraryEntry,
  Template,
  KnowledgeArticle,
  AuditLog,
  AuditVerifyResult,
  Notification,
  DashboardSummary,
  DashboardTrends,
  // Phase 1-2: 電子契約・交渉・義務・検索・Matter・顧問弁護士・労務費
  SigningMethod,
  SigningProvider,
  SigningStatus,
  SigningEnvelope,
  SigningEnvelopeCreate,
  SigningEvent,
  ClauseNegotiationStatus,
  ClauseOwner,
  NegotiationAction,
  NegotiationEvent,
  NegotiationEventCreate,
  ClauseNegotiationState,
  ObligationStatus,
  ObligationType,
  Obligation,
  ObligationCreate,
  RenewalCheck,
  ContractSearchHit,
  MatterStatus,
  MatterPriority,
  MatterType,
  Matter,
  MatterCreate,
  MatterUpdate,
  MatterStatusIn,
  MatterAssignIn,
  MatterNoteIn,
  MatterEvent,
  MatterContract,
  LawFirm,
  LawFirmCreate,
  CounselLawyer,
  CounselLawyerCreate,
  EngagementStatus,
  Engagement,
  EngagementCreate,
  LaborWorkType,
  LaborWageStandard,
  LaborWageStandardCreate,
  LaborWageDiscrepancy,
  ConsultationDirection,
  ConsultationStatus,
  DumpingSeverity,
  PriceConsultationLog,
  PriceConsultationCreate,
  StandardWorkDuration,
  StandardWorkDurationCreate,
  ShortDurationCheck,
  PriceSimulatorIn,
  PriceSimulatorOut,
  AgencyType,
  OwnerNotificationType,
  OwnerNotificationStatus,
  PublicWorksConsultationType,
  PublicWorksConsultationStatus,
  ContractingAgency,
  ContractingAgencyCreate,
  OwnerNotification,
  OwnerNotificationCreate,
  PublicWorksConsultation,
  PublicWorksConsultationCreate,
  StandardClauseCheck,
  PublicWorksDashboard,
} from "@/lib/api/schemas";

export type { ProblemDetails } from "@/lib/api/client";
export { ApiError } from "@/lib/api/client";
